# Noise NK example (client).
# remote_public_key must be the Public Key from the server's rathole --genkey output
# (the public half of local_private_key in server.toml).

[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "mEnUEACy9UrTBmwoCJb6fcKWBRdvfD9XzuBVsroOLFg="

[client.services.foo1]
local_addr = "127.0.0.1:80"
